### ISSUE TITLE
u.$appendTo is not a function

### ISSUE THREAD

**Issue by Lxxyx** [ElemeFE/vue-indicator#11]
正常引入使用，报错。
Vue2.1.0。

**Comment by tmpbook** [comment]
@Lxxyx 兄弟解决了吗？一样的问题

**Comment by tmpbook** [comment]
@Leopoldthecoder HI，如果不花时间，能帮忙解决下吗？

**Comment by wuzi1975** [comment]
遇到同样的问题, 此组件不支持单独使用吗?

**Comment by dyq086** [comment]
@Lxxyx 那个vm.$appendTo 是1.0的方法，已被移除。http://cn.vuejs.org/v2/guide/migration.html#vm-appendTo-移除

**Comment by evanoxu** [comment]
@galenyuan 单独的插件你们是否有更新到支持2.0的计划？

**Comment by antybody** [comment]
把这句话 改成 document.body.appendChild(u.$el)
